<?php
/**
 * 1997-2015 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2015 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<style type="text/css">
    .be2bill-api-notice .url-list {
        padding-top: 15px;
    }

    .be2bill-api-notice .url-list dl.store, .be2bill-api-notice .url-list dl.store ul {
        padding: 5px 10px;
    }
</style>
<?php $params = array('_secure' => true, '_store_to_url' => false) ?>
<div class="be2bill-api-notice">
    <div class="box">
        <ul>
            <li><?php echo $this->__('Magento Connector Version: v%s', (string)Mage::getConfig()->getNode()->modules->Quadra_Be2bill->version) ?></li>
        </ul>
    </div>
    <div class="info">
        <?php echo $this->__('Afin de vous faciliter la saisie des paramètres dans <a href="%s" target="_blank">l\'extranet de Be2bill</a>, vous trouverez ci-dessous la liste des toutes les URLs de votre site.', 'https://extranet.be2bill.com/') ?>
        <br />
        <?php echo $this->__('Ces URLs sont formatées selon la configuration actuelle de Magento.') ?>
    </div>
    <div class="url-list">
        <dl class="website">
            <?php foreach (Mage::app()->getWebsites() as $website): ?>
                <dt><h4><?php echo $this->__('Store Name: %s', $website->getName()) ?></h4></dt>
                <dd>
                    <?php foreach ($website->getStores() as $store): ?>
                        <?php $url = Mage::getModel('core/url')->setStore($store); ?>
                        <dl class="store">
                            <dt><h5><?php echo $this->__('Store View Name: %s', $store->getName()) ?></h5></dt>
                            <dd>
                                <ul>
                                    <li><?php echo $this->__('<strong>URL de notification de transactions : </strong> %s', $url->getUrl('be2bill/payments/ipn', $params)) ?></li>
                                    <li><?php echo $this->__('<strong>URL de notification d’impayés : </strong> %s', $url->getUrl('be2bill/payments/ipn', $params)) ?></li>
                                    <?php //echo $this->__('<strong>URL du modèle de formulaire :</strong> %s ou bien une page CMS contenant la variable %s', $url->getUrl('be2bill/template/ssl', $params), '%PLACEHOLDER%') ?>
                                    <?php //echo $this->__('<strong>URL du modèle de formulaire avec utilisation d\'une iframe :</strong> %s ou bien une page CMS contenant la variable %s', $url->getUrl('be2bill/template/iframe', $params), '%PLACEHOLDER%') ?>
                                    <li><?php echo $this->__('<strong>URL de redirection après un traitement formulaire ou 3DSECURE :</strong> %s', $url->getUrl('be2bill/payments/return', $params)) ?></li>
                                    <li><?php echo $this->__('<strong>URL de redirection lors de l\'annulation d\'un traitement formulaire :</strong> %s', $url->getUrl('be2bill/payments/cancel', $params)) ?></li>
                                </ul>
                            </dd>
                        </dl>
                    <?php endforeach; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    </div>
</div>
