<?php
/**
 * 1997-2016 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2015 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<dl class="sp_methods" id="checkout-payments-be2bill-method-load">
    <?php $paymentsMethod = $this->getAvailablePayments() ?>
    <?php foreach ($paymentsMethod as $paymentsMethod) : ?>
        <?php $options = $paymentsMethod->getAvailableOptions(10); ?>
        <?php foreach ($options as $option) : ?>
            <dt id="dt_method_be2bill_<?php echo $paymentsMethod->getdata('b2b_xml_account_type_code') ?>_<?php echo $option->getdata('b2b_xml_option') ?>">
                <input id="p_method_be2bill_<?php echo $paymentsMethod->getdata('b2b_xml_account_type_code') ?>_<?php echo $option->getdata('b2b_xml_option') ?>" value="be2bill" type="radio" name="payment[method]" title="<?php echo $paymentsMethod->getdata('b2b_xml_account_type_code') . '  :  ' . $option->getData('b2b_xml_option') ?>" onclick="payment.switchMethod('be2bill_<?php echo $paymentsMethod->getdata('b2b_xml_account_type_code') ?>_<?php echo $option->getdata('b2b_xml_option') ?>')" class="radio" autocomplete="off">
                <label for="p_method_be2bill_<?php echo $paymentsMethod->getdata('b2b_xml_account_type_code') ?>_<?php echo $option->getdata('b2b_xml_option') ?>"><?php echo $paymentsMethod->getdata('b2b_xml_account_type_code') . '  :  ' . $option->getData('b2b_xml_option') ?></label>
            </dt>
            <dd id="dd_method_be2bill_<?php echo $paymentsMethod->getdata('b2b_xml_account_type_code') ?>_<?php echo $option->getdata('b2b_xml_option') ?>"></dd>
        <?php endforeach; ?>
    <?php endforeach; ?>
</dl>