<?php
/**
 * 1997-2016 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2015 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<?php if ($this->canOneclick() && ($sAliasSelect = $this->getAliasSelect()) && ($sShippingMethodsSelect = $this->getShippingMethodsSelect())) : ?>
    <div class="be2bill-<?php echo $this->getProduct()->getTypeId() ?>-product-oneclick">
        <div class="be2bill-product-oneclick-content">
            <span class="or"><?php echo $this->__('OU') ?>&nbsp;<?php echo $this->__('Commander en un clic avec Be2bill') ?></span>
            <?php if ($this->customerHasAddresses()): ?>
                <div class="field">
                    <label for="alias-card-select"><?php echo $this->__('Sélectionnez une carte enregistrée') ?></label>
                    <div class="input-box">
                        <?php echo $sAliasSelect; ?>
                    </div>
                </div>
                <div class="field">
                    <label for="shipping-address-select"><?php echo $this->__('Sélectionnez une addresse :') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('shipping') ?>
                    </div>
                </div>
                <div class="field">
                    <label for="shipping-method-select"><?php echo $this->__('Sélectionnez une méthode de livraison :') ?></label>
                    <div class="input-box">
                    <div class="input-box" id="div-shipping-method-select">
                        <?php echo $sShippingMethodsSelect; ?>
                    </div>
                    </div>
                </div>
            <?php endif; ?>
            <span class="please-wait" id="please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__("S'il vous plaît, attendez...") ?>" title="<?php echo $this->__("S'il vous plaît, attendez...") ?>" class="v-middle" /> <?php echo $this->__("S'il vous plaît, attendez...") ?>
            </span>
            <div class="actions">
                <span title="<?php echo $this->__('Pay') ?>" id="ock_button" class="button btn-cart" onclick="productAddToCartForm.submit(this, '<?php echo $this->getOneclickUrl() ?>');"><span><span><?php echo $this->__('Payer') ?></span></span></span>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript" >
// mise à jour de la quantité
$('qty').observe('change', updateShippingFees);

// mise à jour de l'adresse de livraison
$('shipping-address-select').observe('change', updateShippingFees);

// fonction ajax pour mise a jour de la methode de livraison
function updateShippingFees(){
	var productId = '<?php echo $this->getProduct()->getId() ?>';
	var url = '<?php echo Mage::getUrl('be2bill/checkout_oneclick/updateShippingFee'); ?>';
	
	$('shipping-method-select').hide();
	$('ock_button').hide();	
    $('please-wait').show();	
	
	new Ajax.Request(url, {
	    method: 'get',
	    parameters: {productId: productId , qty : $('qty').value , addressId : $('shipping-address-select').value},
	    onSuccess: function(transport) {
	    	
			var elementValues = {};
	        if (transport && transport.responseText){
	            try{
	                elementValues = eval('(' + transport.responseText + ')');
	            }
	            catch (e) {
	                elementValues = {};
	            }
	        }
	    	
	        $('div-shipping-method-select').innerHTML = elementValues.html;
			$('ock_button').show();
			$('please-wait').hide();
	    },
	    onFailure: function(transport) {
	        location.reload;
	    }
	});
}

updateShippingFees();
</script>